-- Random /me actions
INSERT INTO messages (text, category) VALUES ('bounces gently on the soft grass', 'random-actions');
INSERT INTO messages (text, category) VALUES ('lets out a happy "Poring!" sound', 'random-actions');
INSERT INTO messages (text, category) VALUES ('wobbles slightly side-to-side', 'random-actions');
INSERT INTO messages (text, category) VALUES ('basks warmly in a patch of sunlight', 'random-actions');
INSERT INTO messages (text, category) VALUES ('hops twice in excitement', 'random-actions');
INSERT INTO messages (text, category) VALUES ('bumps softly against a friendly Poporing', 'random-actions');
INSERT INTO messages (text, category) VALUES ('jiggles contently', 'random-actions');
INSERT INTO messages (text, category) VALUES ('looks curiously at a passing butterfly', 'random-actions');
INSERT INTO messages (text, category) VALUES ('makes a soft, bubbling noise', 'random-actions');
INSERT INTO messages (text, category) VALUES ('squishes down slightly before bouncing high', 'random-actions');
INSERT INTO messages (text, category) VALUES ('rustles through a patch of fallen leaves', 'random-actions');
INSERT INTO messages (text, category) VALUES ('stares blankly at a tree trunk', 'random-actions');
INSERT INTO messages (text, category) VALUES ('lets out a quiet "po...ring?"', 'random-actions');
INSERT INTO messages (text, category) VALUES ('nudges a stray Jellopy', 'random-actions');
INSERT INTO messages (text, category) VALUES ('sits perfectly still, enjoying the peace', 'random-actions');
INSERT INTO messages (text, category) VALUES ('hops backwards suddenly', 'random-actions');
INSERT INTO messages (text, category) VALUES ('tries to absorb a dewdrop from a leaf', 'random-actions');
INSERT INTO messages (text, category) VALUES ('wobbles its head around, observing', 'random-actions');
INSERT INTO messages (text, category) VALUES ('makes a happy little "Bloop!" sound', 'random-actions');
INSERT INTO messages (text, category) VALUES ('spins slowly in a circle', 'random-actions');
INSERT INTO messages (text, category) VALUES ('plops down softly onto a patch of moss', 'random-actions');
INSERT INTO messages (text, category) VALUES ('quivers slightly as a breeze rustles the leaves', 'random-actions');
INSERT INTO messages (text, category) VALUES ('watches a Novice wander by', 'random-actions');
INSERT INTO messages (text, category) VALUES ('bounces off a large mushroom cap', 'random-actions');
INSERT INTO messages (text, category) VALUES ('lets out a series of small, happy hops', 'random-actions');
INSERT INTO messages (text, category) VALUES ('settles into the grass for a moment', 'random-actions');
INSERT INTO messages (text, category) VALUES ('makes a gurgling sound of contentment', 'random-actions');
INSERT INTO messages (text, category) VALUES ('bumps gently against your ankle', 'random-actions');
INSERT INTO messages (text, category) VALUES ('stretches upwards slightly, then relaxes', 'random-actions');
INSERT INTO messages (text, category) VALUES ('simply enjoys being a Poring in the forest', 'random-actions');
INSERT INTO messages (text, category) VALUES ('rolls slowly down a tiny slope', 'random-actions');
INSERT INTO messages (text, category) VALUES ('slides a little on wet moss', 'random-actions');
INSERT INTO messages (text, category) VALUES ('hops left, then right, then left again', 'random-actions');
INSERT INTO messages (text, category) VALUES ('bounces very, very slowly', 'random-actions');
INSERT INTO messages (text, category) VALUES ('vibrates with a low, quiet hum', 'random-actions');
INSERT INTO messages (text, category) VALUES ('sniffs cautiously at a bright yellow flower', 'random-actions');
INSERT INTO messages (text, category) VALUES ('leans its side against a cool, smooth stone', 'random-actions');
INSERT INTO messages (text, category) VALUES ('peers into its faint reflection in a puddle', 'random-actions');
INSERT INTO messages (text, category) VALUES ('gets briefly stuck near a sticky plant, then pops free', 'random-actions');
INSERT INTO messages (text, category) VALUES ('peeks out shyly from behind a leafy fern', 'random-actions');
INSERT INTO messages (text, category) VALUES ('feels a large dewdrop land on it with a plink', 'random-actions');
INSERT INTO messages (text, category) VALUES ('watches a line of tiny ants march determinedly past', 'random-actions');
INSERT INTO messages (text, category) VALUES ('tilts its body as if listening intently to distant birdsong', 'random-actions');
INSERT INTO messages (text, category) VALUES ('observes a green Fabre munching happily on a leaf', 'random-actions');
INSERT INTO messages (text, category) VALUES ('quickly bounces away from a grumpy-looking Creamy', 'random-actions');
INSERT INTO messages (text, category) VALUES ('accidentally bumps into a sleeping Lunatic, then wobbles away quietly', 'random-actions');
INSERT INTO messages (text, category) VALUES ('notices a colorful Chonchon flutter high above', 'random-actions');
INSERT INTO messages (text, category) VALUES ('ignores a nearby passive Willow completely', 'random-actions');
INSERT INTO messages (text, category) VALUES ('soaks up the gentle warmth radiating from the sun-baked earth', 'random-actions');
INSERT INTO messages (text, category) VALUES ('jumps slightly in surprise as a bird''s shadow passes overhead', 'random-actions');
INSERT INTO messages (text, category) VALUES ('lets out a startled "Po!?" sound', 'random-actions');
INSERT INTO messages (text, category) VALUES ('feels slightly sticky after brushing against sap', 'random-actions');
INSERT INTO messages (text, category) VALUES ('seems to wish it had found a tasty Jellopy', 'random-actions');
INSERT INTO messages (text, category) VALUES ('feels pleasantly full from absorbing sunlight and forest air', 'random-actions');
INSERT INTO messages (text, category) VALUES ('looks around lazily for something interesting to bounce on', 'random-actions');
INSERT INTO messages (text, category) VALUES ('bounces tentatively towards a small, shiny pebble', 'random-actions');
INSERT INTO messages (text, category) VALUES ('quivers for a second, startled by a snapping twig', 'random-actions');
INSERT INTO messages (text, category) VALUES ('gives a little wiggle for no apparent reason', 'random-actions');
INSERT INTO messages (text, category) VALUES ('emits a long, low, drawn-out "Poooooring..."', 'random-actions');
INSERT INTO messages (text, category) VALUES ('hums a tuneless, bubbly, internal song', 'random-actions');
INSERT INTO messages (text, category) VALUES ('makes a sound like a soft, contented sigh', 'random-actions');
INSERT INTO messages (text, category) VALUES ('gurgles quietly to itself', 'random-actions');
INSERT INTO messages (text, category) VALUES ('lets out a tiny squeak after bumping into a sharp rock', 'random-actions');
INSERT INTO messages (text, category) VALUES ('makes a small, satisfying popping sound after a big bounce', 'random-actions');
INSERT INTO messages (text, category) VALUES ('tries to mimic a Fabre''s slow crawl, fails adorably', 'random-actions');
INSERT INTO messages (text, category) VALUES ('attempts to bounce determinedly up a small dirt mound', 'random-actions');
INSERT INTO messages (text, category) VALUES ('leaves a barely visible, slightly slimy trail on a flat rock', 'random-actions');
INSERT INTO messages (text, category) VALUES ('seems to absorb the faint, calming magical energy of the forest', 'random-actions');
INSERT INTO messages (text, category) VALUES ('twitches slightly, perhaps dreaming of giant Jellopies', 'random-actions');
INSERT INTO messages (text, category) VALUES ('rests its lower curve comfortably on the ground', 'random-actions');
INSERT INTO messages (text, category) VALUES ('jiggles excitedly back and forth for a moment', 'random-actions');
INSERT INTO messages (text, category) VALUES ('makes ''eye contact'' with a motionless Pupa', 'random-actions');
INSERT INTO messages (text, category) VALUES ('bounces with a steady, relaxed rhythm', 'random-actions');
INSERT INTO messages (text, category) VALUES ('looks up towards the gently rustling tree canopy', 'random-actions');
INSERT INTO messages (text, category) VALUES ('allows a curious ladybug to crawl slowly over its surface', 'random-actions');
INSERT INTO messages (text, category) VALUES ('taps gently against the side of a hollow log', 'random-actions');
INSERT INTO messages (text, category) VALUES ('wobbles uncertainly before choosing a direction', 'random-actions');
INSERT INTO messages (text, category) VALUES ('does a small, happy tumble that ends in a bounce', 'random-actions');
INSERT INTO messages (text, category) VALUES ('presses itself against the ground, feeling the earth''s vibrations', 'random-actions');
INSERT INTO messages (text, category) VALUES ('lets out a short, sharp burst of "Poring! Poring!"', 'random-actions');
INSERT INTO messages (text, category) VALUES ('seems to ponder the intricate details of a single blade of grass', 'random-actions');
INSERT INTO messages (text, category) VALUES ('squishes carefully underneath a low-hanging, leafy branch', 'random-actions');
INSERT INTO messages (text, category) VALUES ('moves slowly towards the faint sound of dripping water', 'random-actions');
INSERT INTO messages (text, category) VALUES ('suddenly stops bouncing mid-air and listens intently', 'random-actions');
INSERT INTO messages (text, category) VALUES ('jiggles the very top part of its body slightly', 'random-actions');
INSERT INTO messages (text, category) VALUES ('waits patiently near a patch of interesting flowers', 'random-actions');
INSERT INTO messages (text, category) VALUES ('gazes intently at its own slowly moving shadow', 'random-actions');
INSERT INTO messages (text, category) VALUES ('rubs its side gently against a smooth, rounded pebble', 'random-actions');
INSERT INTO messages (text, category) VALUES ('tries, and fails, to catch a gently falling leaf', 'random-actions');
INSERT INTO messages (text, category) VALUES ('makes a soft ''thump'' sound landing after a particularly high bounce', 'random-actions');
INSERT INTO messages (text, category) VALUES ('appears to be meditating, achieving inner Poring peace', 'random-actions');
INSERT INTO messages (text, category) VALUES ('bounces forward in a slow, deliberate zig-zag pattern', 'random-actions');
INSERT INTO messages (text, category) VALUES ('leans slightly to one side, as if listening to the ground', 'random-actions');
INSERT INTO messages (text, category) VALUES ('uses its movement to trace a small, rough circle on the dirt', 'random-actions');
INSERT INTO messages (text, category) VALUES ('releases a single, small, iridescent bubble into the air', 'random-actions');
INSERT INTO messages (text, category) VALUES ('looks slightly deflated for a brief moment, then puffs back up', 'random-actions');
INSERT INTO messages (text, category) VALUES ('tilts rhythmically back and forth like a gooey metronome', 'random-actions');
INSERT INTO messages (text, category) VALUES ('makes a soft, damp squelching sound on wet ground', 'random-actions');
INSERT INTO messages (text, category) VALUES ('observes a fat earthworm wriggling slowly past', 'random-actions');
INSERT INTO messages (text, category) VALUES ('bounces just high enough to peek over a large clump of grass', 'random-actions');
INSERT INTO messages (text, category) VALUES ('seems utterly fascinated by a single dust mote floating in a sunbeam', 'random-actions');
INSERT INTO messages (text, category) VALUES ('gives a tiny, almost imperceptible wiggle that might be a nod', 'random-actions');
INSERT INTO messages (text, category) VALUES ('rests peacefully near the gnarled roots of an ancient tree', 'random-actions');
INSERT INTO messages (text, category) VALUES ('lets out a quiet sound almost like a tiny, happy sigh', 'random-actions');
