CREATE TABLE messages (
    id CHAR(36) PRIMARY KEY NOT NULL DEFAULT (UUID()),
    text VARCHAR(512) NOT NULL,
    category VARCHAR(128) NOT NULL,
    usage_count INT UNSIGNED NOT NULL DEFAULT 0,
    last_used TIMESTAMP NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE timers (
    id VARCHAR(128) PRIMARY KEY NOT NULL,
    execute_at TIMESTAMP NOT NULL,
    executed BOOLEAN NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
